export const examples = {
  "0000_overview": {
    cmpt: require('./0000_overview'),
    content: "import React from 'react'\r\nimport { Text } from '@zecos/input-basic'\r\nimport { validateName } from '@zecos/validate'\r\n\r\n\r\nconst Example = () => {\r\n  const {FirstNameDisplay, FirstName} = Text({\r\n    name: \"firstName\",\r\n    validate: validateName\r\n  })\r\n  \r\n  return (\r\n    <>\r\n      <FirstName /> {/* form input */}\r\n      <FirstNameDisplay full={true} />\r\n    </>\r\n  )\r\n}\r\n\r\nexport default Example"
  },"0010_field": {
    cmpt: require('./0010_field'),
    content: "import React, { useState } from 'react'\r\nimport { field } from '@zecos/field'\r\nimport { validateName } from \"@zecos/validate\"\r\n\r\nconst renderErrors = state => {\r\n  const {touched, errors} = state\r\n  if (touched && errors.length) {\r\n    return (\r\n      <span style={{color: \"red\"}}>\r\n        {errors.map(err => <div>{err.toString()}</div>)}\r\n      </span>\r\n    )\r\n  }\r\n}\r\n\r\nconst Form = () => {\r\n  const [[actions, state], _setFormState] = useState(() => {\r\n    const _field = field({\r\n      init: '',\r\n      validate: validateName,\r\n    })\r\n    return [_field, _field.getState()]\r\n  })\r\n  \r\n  const {\r\n    setValue,\r\n    setTouched,\r\n    reset,\r\n    setState,\r\n    getState\r\n  } = actions\r\n  \r\n  const setFormState = state => _setFormState([actions, state])\r\n  \r\n  const {\r\n    errors,\r\n    value,\r\n    touched,\r\n    pristine\r\n  } = actions.getState()\r\n  \r\n  return (\r\n    <form style={{padding: 20}}>\r\n      <label htmlFor=\"name\">Name: </label>&nbsp;\r\n      <input\r\n        name=\"name\"\r\n        value={value}\r\n        onChange={e => setFormState(setValue(e.target.value))}\r\n        onBlur={_ => setFormState(setTouched())}\r\n      />\r\n      <br />\r\n      {renderErrors(state)}\r\n    </form>\r\n  )\r\n}\r\n\r\nexport default Form\r\n"
  },"0020_create-input": {
    cmpt: require('./0020_create-input'),
    content: "import React from \"react\"\r\nimport { createInput } from '@zecos/input'\r\nimport { validateName } from \"@zecos/validate\"\r\n\r\nconst text = createInput(({helpers, state}) => {\r\n    const {\r\n      id,\r\n      name,\r\n      label,\r\n      handleChange,\r\n      handleBlur,\r\n    } = helpers\r\n    \r\n    const {touched, errors, value} = state\r\n    return (\r\n      <div>\r\n        <label htmlFor={name}>\r\n          {label}: &nbsp;\r\n        {touched && errors[0] && errors[0].toString()}\r\n        </label>\r\n        <input\r\n          name={name}\r\n          aria-label={label}\r\n          onChange={handleChange}\r\n          value={value}\r\n          onBlur={handleBlur}\r\n          id={id}\r\n        />\r\n      </div> \r\n    )\r\n})\r\n\r\nconst Form = () => {\r\n  const {FirstName, FirstNameDisplay} = text({\r\n    name: \"firstName\",\r\n    validate: validateName,\r\n    init: \"Bob\",\r\n  })\r\n\r\n  return (\r\n    <form className=\"form\">\r\n      <FirstName /><br />\r\n      <FirstNameDisplay full={true} />\r\n    </form> \r\n  )\r\n}\r\n\r\nexport default Form"
  },"0030_create-input-select": {
    cmpt: require('./0030_create-input-select'),
    content: "import React from 'react'\r\nimport { createInput } from '@zecos/input'\r\n\r\nconst renderOption = ([key, label]) => {\r\n  return (\r\n    <option key={key} value={key}>\r\n      {label}\r\n    </option>\r\n  )\r\n}\r\n\r\nexport const select = createInput(({helpers, props}) => {\r\n  const {\r\n    id,\r\n    name,\r\n    value,\r\n    handleChange,\r\n    handleBlur,\r\n    label,\r\n    htmlFor,\r\n  } = helpers\r\n\r\n  return (\r\n    <div>\r\n      <label htmlFor={htmlFor}>\r\n        {label}: &nbsp;\r\n      </label>\r\n      <select\r\n        onChange={handleChange}\r\n        onBlur={handleBlur}\r\n        name={name}\r\n        id={id}\r\n        value={value}\r\n        aria-label={label}\r\n      >\r\n        {Object.entries(props.options).map(renderOption)}\r\n      </select>\r\n    </div>\r\n  )\r\n})\r\n\r\nexport const Form = () => {\r\n  const {FavoriteColor, FavoriteColorDisplay} = select({\r\n    init: \"blue\",\r\n    name: \"favoriteColor\",\r\n    props: {\r\n     options: {green: \"Green\", blue: \"Blue\"} \r\n    }\r\n  })\r\n\r\n  return (\r\n    <form className=\"form\">\r\n      <FavoriteColor options={{blue: \"Blue\", red: \"Red\"}} />\r\n      <FavoriteColorDisplay />\r\n    </form>\r\n  )\r\n}\r\n\r\nexport default Form"
  },"0040_create-layout": {
    cmpt: require('./0040_create-layout'),
    content: "import React from 'react'\r\nimport { createLayout } from \"@zecos/input\"\r\nimport { Text, Select, TextArea } from '@zecos/input-basic'\r\nimport { validateName } from '@zecos/validate'\r\n\r\nconst SimpleFormLayout = createLayout(({props, items, errors, helpers}) => {\r\n  return (\r\n    <form {...props}>\r\n      <div>{helpers.title}</div>\r\n      {errors[0] && errors[0].toString()}\r\n      {items.map((Input, i) => (\r\n        <span key={i}><Input.Cmpt key={i} /></span>\r\n      ))}\r\n    </form>\r\n  )\r\n})\r\n\r\nconst Example = () => {\r\n  const { Form, FormDisplay } = SimpleFormLayout({\r\n    name: 'form',\r\n    items: [\r\n      Text({\r\n        validate: validateName,\r\n        name: \"firstName\",\r\n        init: \"Zane\",\r\n      }),\r\n      TextArea({\r\n        name: \"describeYourself\"\r\n      }),\r\n      Select({\r\n        init: \"blue\",\r\n        name: \"favoriteColor\",\r\n        props: {\r\n          options: {\r\n            \"Blue\": \"blue\",\r\n            \"Red\": \"red\",\r\n          }\r\n        }\r\n      })\r\n    ],\r\n    validate: (items:any) => {\r\n      if (items[0].state.value === \"Zane\") {\r\n        return [new Error(\"Name cannot be Zane\")]\r\n      }\r\n      return []\r\n    }\r\n  })\r\n  \r\n  return (\r\n    <div>\r\n      <Form />\r\n      <FormDisplay />\r\n    </div>\r\n  )\r\n}\r\n\r\nexport default Example"
  },"0050_create-multi": {
    cmpt: require('./0050_create-multi'),
    content: "import React from 'react'\r\nimport { createMulti } from '@zecos/input'\r\nimport { Text, GroupLayout } from '@zecos/input-basic'\r\nimport { validateName } from '@zecos/validate'\r\n\r\nconst Multi:any = createMulti(({items, actions, helpers}) => {\r\n  return <>\r\n    {items.map((Input, i) => (\r\n      <div key={i}>\r\n      <Input.Cmpt />\r\n      <button\r\n        style={{display: \"block\"}}\r\n        onClick={() => actions.splice(i, 1)}\r\n      >\r\n        Remove Person\r\n      </button>\r\n      </div>\r\n    ))}\r\n  </>\r\n})\r\n\r\nconst newPerson = () => GroupLayout({\r\n  name: 'person',\r\n  items: [\r\n    Text({\r\n      validate: validateName,\r\n      name: \"firstName\"\r\n    }),\r\n    Text({\r\n      validate: validateName,\r\n      name: \"lastName\",\r\n    }),\r\n  ],\r\n})\r\n\r\nconst MultiForm = () => {\r\n  const {actions, People, PeopleDisplay} = Multi({\r\n    init: [\r\n      newPerson()\r\n    ],\r\n    name: \"people\",\r\n  })\r\n  \r\n  return <div>\r\n      <People />\r\n      <PeopleDisplay />\r\n      <button\r\n        type=\"button\"\r\n        onClick={() => actions.push(newPerson)}\r\n      >\r\n        Add Person\r\n      </button>\r\n    </div>\r\n}\r\n\r\n\r\nexport default MultiForm\r\n"
  },"0060_text-input": {
    cmpt: require('./0060_text-input'),
    content: "import React from \"react\"\r\nimport { validateName } from \"@zecos/validate\"\r\nimport { TextInput} from \"@zecos/input-mui\"\r\n\r\nconst TextInputExample = () => {\r\n  const {FirstName, FirstNameDisplay} = TextInput({\r\n    validate: validateName,\r\n    init: '',\r\n    name: \"firstName\"\r\n  })\r\n\r\n  return (\r\n    <>\r\n    <form className=\"form\">\r\n      <FirstName />\r\n      <FirstNameDisplay />\r\n    </form>\r\n    <br />\r\n    {/* display the data */}\r\n    </>\r\n  )\r\n}\r\n \r\nexport default TextInputExample"
  },"0070_select-input": {
    cmpt: require('./0070_select-input'),
    content: "import React from \"react\"\r\nimport { SelectInput } from \"@zecos/input-mui\"\r\n\r\nconst SelectInputExample = () => {\r\n  const {FavoriteColor, FavoriteColorDisplay} = SelectInput({\r\n    init: \"blue\",\r\n    name: \"favoriteColor\",\r\n  })\r\n\r\n  return (\r\n    <>\r\n    <form className=\"form\">\r\n      <FavoriteColor options={{\r\n        Blue: \"blue\",\r\n        Red: \"red\",\r\n      }}/>\r\n      <FavoriteColorDisplay />\r\n    </form>\r\n    <br />\r\n    {/* display the data */}\r\n    </>\r\n  )\r\n}\r\n \r\nexport default SelectInputExample\r\n"
  },"0080_library-general": {
    cmpt: require('./0080_library-general'),
    content: "import React from 'react'\r\nimport { Text } from '@zecos/input-basic'\r\nimport { validateName } from '@zecos/validate'\r\n\r\n\r\nconst Example = () => {\r\n  const {FirstNameDisplay, Cmpt} = Text({\r\n    name: \"firstName\",\r\n    validate: validateName\r\n  })\r\n  \r\n  return (\r\n    <>\r\n      <Cmpt /> {/* form input */}\r\n      <FirstNameDisplay full={true} />\r\n    </>\r\n  )\r\n}\r\n\r\nexport default Example"
  },"0090_library-replaced": {
    cmpt: require('./0090_library-replaced'),
    content: "import React from 'react'\r\nimport { Text } from '@zecos/input-basic'\r\nimport { validateName } from '@zecos/validate'\r\n\r\n\r\nconst Example = () => {\r\n  const {Display, FirstName, Cmpt, FirstNameDisplay} = Text({\r\n    name: \"firstName\",\r\n    validate: validateName\r\n  })\r\n  console.log(\"display\", Display)\r\n  \r\n  return (\r\n    <>\r\n      <FirstName />\r\n      <Cmpt />  {/* same as above line */}\r\n      <Display full={true} />\r\n      <FirstNameDisplay full={true} /> {/* same as above line */}\r\n      <FirstNameDisplay /> {/* Without the \"full\" property, it just gets the value */}\r\n    </>\r\n  )\r\n}\r\n\r\nexport default Example"
  },"0100_library-logging": {
    cmpt: require('./0100_library-logging'),
    content: "import React from 'react'\r\nimport { Text } from '@zecos/input-basic'\r\nimport { validateName } from '@zecos/validate'\r\nimport { Button } from '@material-ui/core'\r\n\r\n\r\nconst Example = () => {\r\n  const {FirstName, Display, log, logFirstName} = Text({\r\n    name: \"firstName\",\r\n    validate: validateName\r\n  })\r\n  \r\n  return (\r\n    <>\r\n      <FirstName />\r\n      <Display />\r\n      <br />\r\n      <Button variant=\"contained\" onClick={log}>Log First Name Data</Button>\r\n      <br />\r\n      <br />\r\n      <div>These two buttons are equivalent. Check the console.</div>\r\n      <br />\r\n      <Button variant=\"contained\" onClick={logFirstName}>Log First Name Data</Button>\r\n    </>\r\n  )\r\n}\r\n\r\nexport default Example"
  },"0110_basic-text": {
    cmpt: require('./0110_basic-text'),
    content: "import React from 'react'\r\nimport { validateName } from '@zecos/validate'\r\nimport { Text } from '@zecos/input-basic'\r\n\r\nconst Example = () => {\r\n  const { FirstName, FirstNameDisplay } = Text({\r\n    validate: validateName,\r\n    init: 'Harry',\r\n    name: \"firstName\"\r\n  })\r\n\r\n  return (\r\n    <div>\r\n      <FirstName />\r\n      <FirstNameDisplay />\r\n    </div>\r\n  )\r\n}\r\n\r\nexport default Example"
  },"0120_basic-textarea": {
    cmpt: require('./0120_basic-textarea'),
    content: "import React from 'react'\r\nimport { validateName } from '@zecos/validate'\r\nimport { TextArea } from '@zecos/input-basic'\r\n\r\nconst Example = () => {\r\n  const { DescribeYourself, DescribeYourselfDisplay } = TextArea({\r\n    validate: validateName,\r\n    init: 'I am a pretty cool dude...',\r\n    name: \"describeYourself\"\r\n  })\r\n\r\n  return (\r\n    <div>\r\n      <DescribeYourself />\r\n      <DescribeYourselfDisplay />\r\n    </div>\r\n  )\r\n}\r\n\r\nexport default Example"
  },"0130_basic-select": {
    cmpt: require('./0130_basic-select'),
    content: "import React from 'react'\r\nimport { validateName } from '@zecos/validate'\r\nimport { Select } from '@zecos/input-basic'\r\n\r\nconst Example = () => {\r\n  const { FavoriteColor, FavoriteColorDisplay } = Select({\r\n    init: 'blue',\r\n    name: \"favoriteColor\"\r\n  })\r\n\r\n  return (\r\n    <div>\r\n      <FavoriteColor\r\n        options={{\r\n          \"Red\": \"red\",\r\n          \"Blue\": \"blue\",\r\n          \"Purple\": \"purple\",\r\n          \"Black\": \"black\",\r\n        }}\r\n      />\r\n      <FavoriteColorDisplay />\r\n    </div>\r\n  )\r\n}\r\n\r\nexport default Example"
  },"0140_basic-slider": {
    cmpt: require('./0140_basic-slider'),
    content: "import React from 'react'\r\nimport { Slider } from '@zecos/input-basic'\r\n\r\nconst Example = () => {\r\n  const { Angle, AngleDisplay } = Slider({\r\n    init: 0,\r\n    name: \"angle\"\r\n  })\r\n\r\n  return (\r\n    <div>\r\n      <Angle\r\n        min=\"0\"\r\n        max=\"90\"\r\n        step=\"0.5\"\r\n      />\r\n      <AngleDisplay />\r\n    </div>\r\n  )\r\n}\r\n\r\nexport default Example"
  },"0150_basic-checkbox": {
    cmpt: require('./0150_basic-checkbox'),
    content: "import React from 'react'\r\nimport { Checkbox } from '@zecos/input-basic'\r\n\r\nconst Example = () => {\r\n  const { Cool, CoolDisplay } = Checkbox({\r\n    init: true,\r\n    name: \"cool\",\r\n    label: \"I am cool\",\r\n  })\r\n\r\n  return (\r\n    <div>\r\n      <Cool />\r\n      <CoolDisplay />\r\n    </div>\r\n  )\r\n}\r\n\r\nexport default Example"
  },"0160_basic-radio": {
    cmpt: require('./0160_basic-radio'),
    content: "import React from 'react'\r\nimport { Radio } from '@zecos/input-basic'\r\n\r\nconst Example = () => {\r\n  const { FavoriteFlavorOfIceCream, FavoriteFlavorOfIceCreamDisplay } = Radio({\r\n    init: 'chocolate',\r\n    name: \"favoriteFlavorOfIceCream\"\r\n  })\r\n\r\n  return (\r\n    <div>\r\n      <FavoriteFlavorOfIceCream\r\n        options={{\r\n          \"Rocky Road\": \"rockyroad\",\r\n          \"Chocolate\": \"chocolate\",\r\n          \"Vanilla\": \"vanilla\",\r\n        }}\r\n      />\r\n      <FavoriteFlavorOfIceCreamDisplay />\r\n    </div>\r\n  )\r\n}\r\n\r\nexport default Example"
  },"0165_basic-button": {
    cmpt: require('./0165_basic-button'),
    content: "import React from 'react'\r\nimport { Button } from '@zecos/input-basic'\r\n\r\nconst Example = () => {\r\n  const Btn = <Button\r\n    label=\"You can also include the label as a property\"\r\n    onClick={e => {\r\n      e.preventDefault()\r\n      window.alert(\"as well as the onClick property\")\r\n    }}\r\n  />\r\n  return (\r\n    <div style={{color: \"#2E3440\"}}> {/* color is inherited from the parent */}\r\n      <Button\r\n        onClick={e => {\r\n          e.preventDefault()\r\n          window.alert(\"You clicked me!\")\r\n        }}\r\n      >\r\n        Click Me\r\n      </Button>\r\n      {Btn}\r\n    </div>\r\n  )\r\n}\r\n\r\nexport default Example"
  },"0170_basic-group-layout": {
    cmpt: require('./0170_basic-group-layout'),
    content: "import React from 'react'\r\nimport { Checkbox, GroupLayout } from '@zecos/input-basic'\r\n\r\nconst Example = () => {\r\n  const { BandsILike, BandsILikeDisplay } = GroupLayout({\r\n    name: \"bandsILike\",\r\n    items: [\r\n      Checkbox({\r\n        name: \"blink182\",\r\n        init: false,\r\n      }),\r\n      Checkbox({\r\n        name: \"sum41\",\r\n        init: false,\r\n      }),\r\n      Checkbox({\r\n        name: \"redHotChiliPeppers\",\r\n        init: false,\r\n      }),\r\n    ],\r\n    validate: (items) => {\r\n      const totalLiked = items.reduce((acc, item) => acc + Number(item.state.value))\r\n      if (totalLiked > 2) {\r\n        return [new Error(\"Pick no more than 2.\")]\r\n      }\r\n      return []\r\n    }\r\n  })\r\n  \r\n  return (\r\n    <div>\r\n      <BandsILike />\r\n      <br />\r\n      <BandsILikeDisplay />\r\n    </div>\r\n  )\r\n}\r\n\r\nexport default Example"
  },"0180_basic-simple-form": {
    cmpt: require('./0180_basic-simple-form'),
    content: "import React from 'react'\r\nimport { validateUsername, validatePassword } from \"@zecos/validate\"\r\nimport { Text, SimpleForm } from \"@zecos/input-basic\"\r\n\r\nconst SignInCmpt = () => {\r\n    const {SignIn, handleErrors /* with aliases Cmpt, signInHandleErrors */}  = SimpleForm({\r\n        name: 'signIn',\r\n        items: [\r\n            Text({\r\n                validate: validateUsername,\r\n                name: \"username\",\r\n                init: \"\", // defaults to blank\r\n            }),\r\n            Text({\r\n                validate: validatePassword,\r\n                name: \"password\",\r\n                init: \"\",\r\n            }),\r\n        ],\r\n        action: ({values}) => {\r\n            return fetch(\"/api/sign-in\", {\r\n                method: \"POST\",\r\n                headers: {\r\n                    \"Content-Type\": \"application/json\",\r\n                },\r\n                body: JSON.stringify(values())\r\n            })\r\n            .then(handleErrors) // handle errors automatically displays the error for you\r\n            .then(() => window.location.href = \"/\") // redirect to home page, however you do that\r\n            .catch(()=>{ /* already handled for you */})\r\n        },\r\n        loadingText: \"Signing In...\" // customize the button text while it's loading\r\n    })\r\n\r\n    return (\r\n        <div style={{width: \"400px\", margin: \"0 auto\"}}>\r\n            {SignIn}\r\n        </div>\r\n    )\r\n}\r\n\r\nexport default SignInCmpt"
  },"0190_basic-multi": {
    cmpt: require('./0190_basic-multi'),
    content: "import React from 'react'\r\nimport { Text, GroupLayout, Multi } from '@zecos/input-basic'\r\nimport { validateName } from '@zecos/validate'\r\n\r\nconst newPerson = () => GroupLayout({\r\n  name: 'person',\r\n  items: [\r\n    Text({\r\n      validate: validateName,\r\n      name: \"firstName\"\r\n    }),\r\n    Text({\r\n      validate: validateName,\r\n      name: \"lastName\",\r\n    }),\r\n  ],\r\n})\r\n\r\nconst MultiForm = () => {\r\n  const {actions, People, PeopleDisplay} = Multi({\r\n    init: [\r\n      newPerson()\r\n    ],\r\n    name: \"people\",\r\n  })\r\n  \r\n  return <div>\r\n      <People />\r\n      <PeopleDisplay />\r\n      <button type=\"button\" onClick={() => actions.push(newPerson)}>Add Person</button>\r\n    </div>\r\n}\r\n\r\n\r\nexport default MultiForm\r\n"
  },"0200_mui-radio": {
    cmpt: require('./0200_mui-radio'),
    content: "import React from \"react\"\r\nimport { RadioInput} from \"@zecos/input-mui\"\r\n\r\nconst Example = () => {\r\n  const {FavoriteFlavor, FavoriteFlavorDisplay} = RadioInput({\r\n    init: \"rockyroad\",\r\n    name: \"favoriteFlavor\",\r\n    label: \"Favorite Flavor of Ice Cream\",\r\n  })\r\n\r\n  return (\r\n    <>\r\n    <form className=\"form\">\r\n      <FavoriteFlavor\r\n        options={{\r\n          \"Rocky Road\": \"rockyroad\",\r\n          Chocolate: \"chocolate\",\r\n          Vanilla: \"vanilla\",\r\n        }}\r\n      />\r\n      <FavoriteFlavorDisplay />\r\n    </form>\r\n    <br />\r\n    {/* display the data */}\r\n    </>\r\n  )\r\n}\r\n \r\nexport default Example"
  },"0210_mui-checkbox": {
    cmpt: require('./0210_mui-checkbox'),
    content: "import React from 'react'\r\nimport { CheckboxInput } from '@zecos/input-mui'\r\n\r\nconst Example = () => {\r\n  const { Cool, CoolDisplay } = CheckboxInput({\r\n    init: true,\r\n    name: \"cool\",\r\n    label: \"I am cool\",\r\n  })\r\n\r\n  return (\r\n    <div>\r\n      <Cool />\r\n      <CoolDisplay />\r\n    </div>\r\n  )\r\n}\r\n\r\nexport default Example"
  },"0220_mui-switch": {
    cmpt: require('./0220_mui-switch'),
    content: "import React from 'react'\r\nimport { SwitchInput } from '@zecos/input-mui'\r\n\r\nconst Example = () => {\r\n  const {Light, LightDisplay, state } = SwitchInput({\r\n    init: false,\r\n    name: \"light\",\r\n  })\r\n  \r\n  const style = {\r\n    background: state.value ? \"yellow\" : \"black\",\r\n    color: state.value ? \"black\" : \"white\",\r\n    padding: 15,\r\n    borderRadius: 4,\r\n  }\r\n\r\n  return (\r\n    <div style={style}>\r\n      <Light />\r\n      <LightDisplay />\r\n    </div>\r\n  )\r\n}\r\n\r\nexport default Example"
  },"0230_mui-slider": {
    cmpt: require('./0230_mui-slider'),
    content: "import React from 'react'\r\nimport { SliderInput } from '@zecos/input-mui'\r\n\r\nconst Example = () => {\r\n  const {Temperature, TemperatureDisplay} = SliderInput({\r\n    init: 30,\r\n    name: 'temperature',\r\n    props: {\r\n      min: 0,\r\n      max: 100,\r\n      step: 10,\r\n      marks: [...new Array(11)]\r\n        .map((_, num) => ({\r\n          label: `${num * 10}°C`,\r\n          value: num * 10\r\n        })),\r\n    }\r\n  })\r\n  \r\n  const {TemperatureVertical, TemperatureVerticalDisplay} = SliderInput({\r\n    init: 30,\r\n    name: 'temperatureVertical',\r\n    props: {\r\n      min: 0,\r\n      max: 100,\r\n      step: 10,\r\n      orientation: \"vertical\",\r\n      marks: [...new Array(11)]\r\n        .map((_, num) => ({\r\n          label: `${num * 10}°C`,\r\n          value: num * 10\r\n        })),\r\n    }\r\n  })\r\n\r\n  return (\r\n    <div>\r\n      <Temperature />\r\n      <br />\r\n      <TemperatureVertical />\r\n      <TemperatureDisplay />\r\n      <TemperatureVerticalDisplay />\r\n    </div>\r\n  )\r\n}\r\n\r\nexport default Example"
  },"0240_mui-group-layout": {
    cmpt: require('./0240_mui-group-layout'),
    content: "import React from 'react'\r\nimport { CheckboxInput, GroupLayout } from '@zecos/input-mui'\r\n\r\nconst Example = () => {\r\n  const { BandsILike, BandsILikeDisplay } = GroupLayout({\r\n    name: \"bandsILike\",\r\n    items: [\r\n      CheckboxInput({\r\n        init: false,\r\n        name: \"systemOfADown\",\r\n      }),\r\n      CheckboxInput({\r\n        init: false,\r\n        name: \"blink182\",\r\n      }),\r\n      CheckboxInput({\r\n        init: false,\r\n        name: \"sum41\"\r\n      }),\r\n    ],\r\n    validate: (items) => {\r\n      const totalLiked = items.reduce((acc, item) => (\r\n        acc + Number(item.state.value)\r\n      ), 0)\r\n      if (totalLiked > 2) {\r\n        return [new Error(\"Pick no more than 2.\")]\r\n      }\r\n      return []\r\n    }\r\n  })\r\n\r\n  return (\r\n    <div>\r\n      <BandsILike />\r\n      <br />\r\n      <BandsILikeDisplay />\r\n    </div>\r\n  )\r\n}\r\n\r\nexport default Example"
  },"0250_mui-simple-form-layout": {
    cmpt: require('./0250_mui-simple-form-layout'),
    content: "import React from 'react'\r\nimport {\r\n  TextInput,\r\n  SelectInput,\r\n  RadioInput,\r\n  CheckboxInput,\r\n  GroupLayout,\r\n  SimpleFormLayout,\r\n  SwitchInput,\r\n  SliderInput,\r\n} from '@zecos/input-mui'\r\nimport { validateName } from '@zecos/validate'\r\n\r\nconst Example = () => {\r\n  const { MyForm, MyFormDisplay } = SimpleFormLayout({\r\n    name: \"myForm\",\r\n    items: [\r\n      TextInput({\r\n        validate: validateName,\r\n        init: '',\r\n        name: \"firstName\"\r\n      }),\r\n      TextInput({\r\n        validate: validateName,\r\n        init: '',\r\n        name: \"lastName\"\r\n      }),\r\n      SelectInput({\r\n        init: \"blue\",\r\n        name: \"favoriteColor\",\r\n        label: \"What is your favorite color?\",\r\n        props: {\r\n          options: {\r\n            Blue: \"blue\",\r\n            Red: \"red\",\r\n            Pink: \"pink\",\r\n            Purple: \"purple\",\r\n          }\r\n        }\r\n      }),\r\n      RadioInput({\r\n        init: \"rockyroad\",\r\n        name: \"favoriteFlavor\",\r\n        label: \"Favorite Flavor of Ice Cream\",\r\n        props: {\r\n          options: {\r\n            \"Rocky Road\": \"rockyroad\",\r\n            Chocolate: \"chocolate\",\r\n            Vanilla: \"vanilla\",\r\n          }\r\n        },\r\n      }),\r\n      CheckboxInput({\r\n        init: true,\r\n        name: \"cool\",\r\n        label: \"I am cool\",\r\n      }),\r\n      SwitchInput({\r\n        init: false,\r\n        name: \"light\",\r\n      }),\r\n      SliderInput({\r\n        init: 30,\r\n        name: 'temperatureVertical',\r\n        props: {\r\n          min: 0,\r\n          max: 100,\r\n          step: 10,\r\n          marks: [...new Array(11)]\r\n            .map((_, num) => ({\r\n              label: `${num * 10}°C`,\r\n              value: num * 10\r\n            })),\r\n        }\r\n      }),\r\n      GroupLayout({\r\n        name: \"bandsILike\",\r\n        items: [\r\n          CheckboxInput({\r\n            init: false,\r\n            name: \"systemOfADown\",\r\n          }),\r\n          CheckboxInput({\r\n            init: false,\r\n            name: \"blink182\",\r\n          }),\r\n          CheckboxInput({\r\n            init: false,\r\n            name: \"sum41\"\r\n          }),\r\n        ],\r\n        validate: (items) => {\r\n          const totalLiked = items.reduce((acc, item) => (\r\n            acc + Number(item.state.value)\r\n          ), 0)\r\n          if (totalLiked > 2) {\r\n            return [new Error(\"Pick no more than 2.\")]\r\n          }\r\n          return []\r\n        }\r\n      })\r\n    ],\r\n  })\r\n  \r\n  const handleSubmit = e => {\r\n    e.preventDefault()\r\n    window.alert(\"Submitted sucessfully!\")\r\n  }\r\n  \r\n  return (\r\n    <div>\r\n      <MyForm onSubmit={handleSubmit} />\r\n      <br />\r\n      <MyFormDisplay />\r\n    </div>\r\n  )\r\n}\r\n\r\nexport default Example"
  },"0260_mui-multi": {
    cmpt: require('./0260_mui-multi'),
    content: "import React from 'react'\r\nimport { TextInput, GroupLayout, Multi } from '@zecos/input-mui'\r\nimport { Button } from \"@material-ui/core\"\r\nimport { validateName } from '@zecos/validate'\r\n\r\nconst newPerson = () => GroupLayout({\r\n  name: 'friend',\r\n  items: [\r\n    TextInput({\r\n      validate: validateName,\r\n      name: \"firstName\"\r\n    }),\r\n    TextInput({\r\n      validate: validateName,\r\n      name: \"lastName\",\r\n    }),\r\n  ],\r\n})\r\n\r\nconst MultiForm = () => {\r\n  const {actions, Friends, FriendsDisplay} = Multi({\r\n    init: [\r\n      newPerson()\r\n    ],\r\n    name: \"friends\",\r\n  })\r\n  \r\n  return <div>\r\n      <Friends />\r\n      <br />\r\n      <Button\r\n        type=\"button\"\r\n        variant=\"outlined\"\r\n        onClick={() => actions.push(newPerson)}\r\n      >\r\n        Add Person\r\n      </Button>\r\n      <br />\r\n      <br />\r\n      <FriendsDisplay />\r\n    </div>\r\n}\r\n\r\nexport default MultiForm"
  },"0270_mui-date-picker": {
    cmpt: require('./0270_mui-date-picker'),
    content: "import React from 'react'\r\nimport { DatePickerInput } from '@zecos/input-picker'\r\n\r\nconst MultiForm = () => {\r\n  const {AppointmentDate, AppointmentDateDisplay} = DatePickerInput({\r\n    init: new Date,\r\n    name: 'appointmentDate'\r\n  })\r\n  \r\n  return <div>\r\n    <AppointmentDate />\r\n    <AppointmentDateDisplay />\r\n    </div>\r\n}\r\n\r\nexport default MultiForm"
  },"0280_mui-time-picker": {
    cmpt: require('./0280_mui-time-picker'),
    content: "import React from 'react'\r\nimport { TimePickerInput } from '@zecos/input-picker'\r\n\r\nconst MultiForm = () => {\r\n  const {AppointmentTime, AppointmentTimeDisplay} = TimePickerInput({\r\n    init: new Date,\r\n    name: 'appointmentTime'\r\n  })\r\n  \r\n  return <div>\r\n    <AppointmentTime />\r\n    <AppointmentTimeDisplay />\r\n    </div>\r\n}\r\n\r\nexport default MultiForm"
  },"0290_get-values": {
    cmpt: require('./0290_get-values'),
    content: "import React from 'react'\r\nimport { validateName } from \"@zecos/validate\"\r\nimport { Text } from \"@zecos/input-basic\"\r\nimport { getValues } from '@zecos/util'\r\n\r\nconst SignInCmpt = () => {\r\n    const { FirstName, firstName } = Text({\r\n        validate: validateName,\r\n        init: 'Harry',\r\n        name: \"firstName\"\r\n    })\r\n\r\n    const { MiddleName,  middleName } = Text({\r\n        validate: validateName,\r\n        init: 'James',\r\n        name: \"middleName\"\r\n    })\r\n\r\n    const { LastName,  lastName } = Text({\r\n        validate: validateName,\r\n        init: 'Potter',\r\n        name: \"lastName\"\r\n    })\r\n\r\n    const items = [firstName, middleName, lastName]\r\n\r\n    const singleValue = getValues(items, \"firstName\")\r\n    const multipleValues = getValues(items, \"firstName\", \"lastName\")\r\n    const alsoMultipleValues = getValues(items, [\"firstName\", \"lastName\"])\r\n    const allValues = getValues(items)\r\n\r\n    // output prettier\r\n    const neatify = obj => <pre>{JSON.stringify(obj, null, 2)}</pre>\r\n\r\n    return (\r\n        <div>\r\n            <FirstName />\r\n            <LastName />\r\n            <br />\r\n            Single Value: {neatify(singleValue)}\r\n            <br />\r\n            Multiple Values: {neatify(multipleValues)}\r\n            <br />\r\n            Also Multiple Values: {neatify(alsoMultipleValues)}\r\n            <br />\r\n            All Values: {neatify(allValues)}\r\n        </div>\r\n    )\r\n}\r\n\r\nexport default SignInCmpt\r\n"
  }
}